# Generated by Django 4.2.7 on 2025-08-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('unit_name', models.CharField(default='usage', max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usage_categories',
                'ordering': ['sort_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='UsageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usage_configurations',
            },
        ),
        migrations.CreateModel(
            name='UserUsageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(blank=True, max_length=50)),
                ('monthly_limit', models.JSONField(default=dict, help_text='Monthly limits per metric')),
                ('notification_preferences', models.JSONField(default=dict)),
                ('usage_tracking_enabled', models.BooleanField(default=True)),
                ('billing_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_usage_profiles',
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_counted', models.BooleanField(default=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='usage_tracking.usagecategory')),
            ],
            options={
                'db_table': 'usage_metrics',
                'ordering': ['sort_order', 'metric_name'],
                'unique_together': {('category', 'metric_code')},
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('access', 'Feature Access'), ('action', 'Action Performed'), ('creation', 'Resource Created'), ('modification', 'Resource Modified'), ('deletion', 'Resource Deleted'), ('view', 'Resource Viewed'), ('export', 'Data Exported'), ('import', 'Data Imported'), ('api_call', 'API Call Made'), ('report_generated', 'Report Generated')], default='action', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage_tracking.usagemetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_events',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='usage_event_user_id_0432c4_idx'), models.Index(fields=['metric', 'timestamp'], name='usage_event_metric__79105f_idx'), models.Index(fields=['timestamp'], name='usage_event_timesta_6ccc38_idx'), models.Index(fields=['is_processed'], name='usage_event_is_proc_bcae47_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('limit_warning', 'Approaching Limit'), ('limit_exceeded', 'Limit Exceeded'), ('unusual_activity', 'Unusual Activity'), ('high_usage', 'High Usage Detected'), ('billing_threshold', 'Billing Threshold Reached')], max_length=20)),
                ('alert_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usage_tracking.usagemetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_alerts',
                'indexes': [models.Index(fields=['user', 'is_read'], name='usage_alert_user_id_1bde94_idx'), models.Index(fields=['alert_level', 'is_read'], name='usage_alert_alert_l_962f4e_idx'), models.Index(fields=['created_at'], name='usage_alert_created_ff54ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_usage_count', models.IntegerField(default=0)),
                ('total_billable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_data', models.JSONField(default=dict)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_usage_summaries',
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='monthly_usa_user_id_a3ac43_idx'), models.Index(fields=['year', 'month'], name='monthly_usa_year_3e2f19_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usage_count', models.IntegerField(default=0)),
                ('billable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage_tracking.usagemetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_usage_records',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_usage_user_id_289e82_idx'), models.Index(fields=['metric', 'date'], name='daily_usage_metric__aea99d_idx'), models.Index(fields=['date'], name='daily_usage_date_ee8276_idx')],
                'unique_together': {('user', 'metric', 'date')},
            },
        ),
    ]
