# Generated by Django 5.2.15 on 2026-07-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allopathy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allopathyanalysis',
            new_name='allopathy_a_analysi_769e46_idx',
            old_name='allopathy_analyses_analysis_type_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathyanalysis',
            new_name='allopathy_a_status_e7b5e1_idx',
            old_name='allopathy_analyses_status_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathyanalysis',
            new_name='allopathy_a_created_b7d237_idx',
            old_name='allopathy_analyses_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathyfile',
            new_name='allopathy_f_categor_73a3c8_idx',
            old_name='allopathy_files_category_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathyfile',
            new_name='allopathy_f_upload__705752_idx',
            old_name='allopathy_files_upload_date_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathyfile',
            new_name='allopathy_f_status_83e6ad_idx',
            old_name='allopathy_files_status_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathypatients3',
            new_name='allopathy_p_patient_1b4ba3_idx',
            old_name='allopathy_patients_s3_patient_id_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathypatients3',
            new_name='allopathy_p_admissi_a9c1d6_idx',
            old_name='allopathy_patients_s3_admission_date_idx',
        ),
        migrations.RenameIndex(
            model_name='allopathypatients3',
            new_name='allopathy_p_status_f2b8bd_idx',
            old_name='allopathy_patients_s3_status_idx',
        ),
    ]
