# Generated by Django 5.2.4 on 2025-07-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20250724_1647'),
    ]

    operations = [
    ]
