# Generated by Django 5.2.4 on 2025-07-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20250724_1650'),
    ]

    operations = [
    ]
