# Generated by Django 5.2.4 on 2025-07-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_add_fullname_field'),
        ('hospital', '0004_auto_20250730_1059'),
    ]

    operations = [
    ]
