# Generated by Django 4.2.7 on 2025-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patientprofile_staffprofile_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist')], max_length=20, null=True),
        ),
    ]
