# Generated by Django 4.2.7 on 2025-08-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_features', models.JSONField(default=list, help_text='List of selected feature codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('medicine', 'General Medicine'), ('dentistry', 'Dentistry'), ('dermatology', 'Dermatology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('patients', 'Patient Management'), ('subscriptions', 'Subscription Management'), ('hospital', 'Hospital Management'), ('secureneat', 'SecureNeat Security'), ('appointments', 'Appointment Scheduling'), ('billing', 'Billing & Payments'), ('reports', 'Reports & Analytics'), ('emergency', 'Emergency Services'), ('pharmacy', 'Pharmacy Management'), ('lab_tests', 'Laboratory Tests'), ('imaging', 'Medical Imaging'), ('telemedicine', 'Telemedicine'), ('ai_diagnosis', 'AI-Powered Diagnosis'), ('diabetes_management', 'Diabetes Management'), ('cancer_detection', 'Cancer Detection')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Access',
                'verbose_name_plural': 'Feature Access',
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
