# Generated by Django 4.2.7 on 2025-08-12 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_userfeatureprofile_featureaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Whether quota limits are enabled')),
                ('max_total_users', models.PositiveIntegerField(default=50)),
                ('max_doctors', models.PositiveIntegerField(default=10)),
                ('max_nurses', models.PositiveIntegerField(default=15)),
                ('max_patients', models.PositiveIntegerField(default=20)),
                ('max_pharmacists', models.PositiveIntegerField(default=5)),
                ('quota_reset_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_total_users', models.PositiveIntegerField(default=0)),
                ('current_doctors', models.PositiveIntegerField(default=0)),
                ('current_nurses', models.PositiveIntegerField(default=0)),
                ('current_patients', models.PositiveIntegerField(default=0)),
                ('current_pharmacists', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_manage_departments', models.BooleanField(default=True)),
                ('can_access_billing', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_access_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminDashboardFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_management', models.BooleanField(default=True)),
                ('patient_management', models.BooleanField(default=True)),
                ('doctor_management', models.BooleanField(default=False)),
                ('nurse_management', models.BooleanField(default=False)),
                ('pharmacist_management', models.BooleanField(default=False)),
                ('medicine_module', models.BooleanField(default=False)),
                ('dentistry_module', models.BooleanField(default=False)),
                ('dermatology_module', models.BooleanField(default=False)),
                ('pathology_module', models.BooleanField(default=False)),
                ('radiology_module', models.BooleanField(default=False)),
                ('subscription_management', models.BooleanField(default=False)),
                ('billing_reports', models.BooleanField(default=False)),
                ('financial_dashboard', models.BooleanField(default=False)),
                ('system_settings', models.BooleanField(default=False)),
                ('audit_logs', models.BooleanField(default=False)),
                ('user_analytics', models.BooleanField(default=True)),
                ('medical_reports', models.BooleanField(default=False)),
                ('revenue_reports', models.BooleanField(default=False)),
                ('appointment_analytics', models.BooleanField(default=False)),
                ('inventory_reports', models.BooleanField(default=False)),
                ('create_user', models.BooleanField(default=True)),
                ('schedule_appointment', models.BooleanField(default=False)),
                ('generate_report', models.BooleanField(default=True)),
                ('backup_system', models.BooleanField(default=False)),
                ('send_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_features', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
