# Generated by Django 4.2.7 on 2025-08-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_add_missing_modules'),
        ('hospital', '0009_usercreationquota_adminpermissions_and_more'),
    ]

    operations = [
    ]
