# Generated by Django 4.2.7 on 2025-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_merge_20250813_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='cosmetology_module',
            field=models.BooleanField(default=False),
        ),
    ]
