# Generated by Django 4.2.7 on 2025-08-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_notification_system'),
        ('hospital', '0011_admindashboardfeatures_cosmetology_module'),
    ]

    operations = [
    ]
