# Generated by Django 5.2.4 on 2025-08-25 06:06
# Production database already has these fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_merge_20250820_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='add_doctors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='all_doctors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='clinic_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='doctor_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindashboardfeatures',
            name='hospital_management',
            field=models.BooleanField(default=False),
        ),
    ]
