# Generated by Django 4.2.7 on 2025-08-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_admindashboardfeatures_add_doctors_and_more'),
        ('hospital', '0013_fix_migration_sequence'),
    ]

    operations = [
    ]
