# Generated by Django 4.2.7 on 2025-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0014_merge_20250828_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account lockout expiration", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Failed login attempt counter"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_login_completed",
            field=models.BooleanField(
                default=False, help_text="Whether user has completed first login setup"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_change_required",
            field=models.BooleanField(
                default=False, help_text="Force password change on next login"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="Last password change timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="temp_password_expires",
            field=models.DateTimeField(
                blank=True, help_text="Temporary password expiration", null=True
            ),
        ),
    ]
