# Generated by Django 5.2.4 on 2025-07-23 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_type', models.CharField(choices=[('anonymization', 'Anonymization'), ('report_analysis', 'Report Analysis')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('redacted_item_counts', models.JSONField(blank=True, help_text="e.g., {'Patient Names': 2, 'Dates': 1}", null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('error_distribution', models.JSONField(blank=True, help_text="e.g., {'Medical Errors': 1, 'Typos': 2}", null=True)),
                ('input_preview', models.TextField(blank=True, help_text='Snippet of input text', null=True)),
                ('output_preview', models.TextField(blank=True, help_text='Snippet of output/anonymized text or summary of analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
