# Generated by Django 4.2.7 on 2025-08-28 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_prefix', models.CharField(max_length=100, unique=True)),
                ('storage_quota_gb', models.IntegerField(default=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('s3_patient_prefix', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_study_date', models.DateTimeField(blank=True, null=True)),
                ('total_studies', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='radiology.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('institution', 'patient_code')},
            },
        ),
        migrations.CreateModel(
            name='RadiologyStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('study_instance_uid', models.CharField(blank=True, max_length=100, unique=True)),
                ('modality', models.CharField(choices=[('CT', 'Computed Tomography'), ('MRI', 'Magnetic Resonance Imaging'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('PET', 'Positron Emission Tomography'), ('MG', 'Mammography'), ('CR', 'Computed Radiography'), ('DR', 'Digital Radiography'), ('FL', 'Fluoroscopy'), ('DX', 'Digital X-Ray'), ('OTHER', 'Other')], max_length=10)),
                ('body_part', models.CharField(max_length=100)),
                ('study_description', models.TextField()),
                ('clinical_indication', models.TextField(blank=True)),
                ('study_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reported', 'Reported'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('s3_study_prefix', models.CharField(max_length=300)),
                ('dicom_file_count', models.IntegerField(default=0)),
                ('total_file_size_mb', models.FloatField(default=0.0)),
                ('has_report', models.BooleanField(default=False)),
                ('has_ai_analysis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='radiology.radiologypatient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(default='radiology', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('s3_report_key', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='radiology.radiologystudy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('rads_calculator', 'RADS Calculator'), ('report_correction', 'Report Correction'), ('image_analysis', 'Image Analysis'), ('anomaly_detection', 'Anomaly Detection'), ('measurement', 'Automated Measurement'), ('classification', 'Image Classification'), ('segmentation', 'Image Segmentation'), ('other', 'Other Analysis')], max_length=50)),
                ('ai_model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('has_flags', models.BooleanField(default=False)),
                ('s3_analysis_key', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='radiology.radiologystudy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specializations', models.JSONField(default=list)),
                ('s3_workspace_prefix', models.CharField(max_length=300)),
                ('total_reports_created', models.IntegerField(default=0)),
                ('total_ai_analyses', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.institution')),
            ],
            options={
                'unique_together': {('doctor', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('upload', 'Upload')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='radiology_a_resourc_bfe95a_idx'), models.Index(fields=['user', 'created_at'], name='radiology_a_user_id_216f47_idx'), models.Index(fields=['institution', 'created_at'], name='radiology_a_institu_202fc5_idx')],
            },
        ),
    ]
