# Generated by Django 4.2.7 on 2025-08-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_diabetespatient_hba1crecord_diabetesmedication_and_more'),
    ]

    operations = [
    ]
