# Generated by Django 5.2.15 on 2026-07-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNASample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('analysis_id', models.CharField(blank=True, max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('sequencing_type', models.CharField(blank=True, max_length=100)),
                ('analysis_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('coverage', models.CharField(blank=True, max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('total_reads', models.CharField(blank=True, max_length=20)),
                ('mapped_reads', models.CharField(blank=True, max_length=20)),
                ('mapping_rate', models.FloatField(blank=True, null=True)),
                ('total_variants', models.IntegerField(default=0)),
                ('snvs', models.IntegerField(default=0)),
                ('indels', models.IntegerField(default=0)),
                ('high_impact', models.IntegerField(default=0)),
                ('moderate_impact', models.IntegerField(default=0)),
                ('low_impact', models.IntegerField(default=0)),
                ('pathogenic', models.IntegerField(default=0)),
                ('likely_pathogenic', models.IntegerField(default=0)),
                ('vus', models.IntegerField(default=0)),
                ('benign', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNAVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.BigIntegerField()),
                ('ref', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('gene', models.CharField(max_length=50)),
                ('variant_type', models.CharField(max_length=20)),
                ('impact', models.CharField(max_length=20)),
                ('consequence', models.CharField(max_length=100)),
                ('clinical_significance', models.CharField(max_length=50)),
                ('allele_frequency', models.FloatField(blank=True, null=True)),
                ('coverage', models.IntegerField(blank=True, null=True)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('genotype', models.CharField(blank=True, max_length=20)),
                ('dbsnp_id', models.CharField(blank=True, max_length=50)),
                ('cosmic_id', models.CharField(blank=True, max_length=50)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_records', to='dna_sequencing.dnasample')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
