# Generated by Django 5.2.15 on 2026-07-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequencing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasample',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dnasample',
            name='technician',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dnasample',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('processing', 'Processing'), ('sequencing', 'Sequencing'), ('analysis', 'Analysis'), ('completed', 'Completed'), ('failed', 'QC Failed'), ('on_hold', 'On Hold')], default='received', max_length=20),
        ),
    ]
